# Generated by Django 5.2.12 on 2026-03-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='correct_answer_sheet',
            field=models.FileField(blank=True, null=True, upload_to='correct_answer_sheets/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_paper',
            field=models.FileField(blank=True, null=True, upload_to='question_papers/'),
        ),
    ]
